project:
  type: website
  output-dir: docs

website:
  title: "Sarah Medley"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - experience.qmd

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true
    page-layout: full
    fontsize: 1.1em
    linestretch: 1.7

editor: visual

